name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # هر روز ساعت 00:00 UTC اجرا میشه
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: Mahdi-jahanfar-dev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the file
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
